services:
  - type: web
    name: autostatiq
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 300 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: OPENAI_API_KEY
        sync: false
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
    healthCheckPath: /health
    autoDeploy: true
    region: oregon
    scaling:
      minInstances: 1
      maxInstances: 3
